# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jewelery-customizer"
client_id = "ca7fdd742942060d1df68ad05994e403"
application_url = "https://extends-syndicate-silence-municipal.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://extends-syndicate-silence-municipal.trycloudflare.com/auth/callback",
  "https://extends-syndicate-silence-municipal.trycloudflare.com/auth/shopify/callback",
  "https://extends-syndicate-silence-municipal.trycloudflare.com/api/auth/callback",
  "https://extends-syndicate-silence-municipal.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-63fa2cb2.myshopify.com"
